# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('leader', models.CharField(max_length=10, verbose_name='负责人')),
                ('addr', models.CharField(max_length=64, verbose_name='地址')),
                ('zipcode', models.IntegerField(verbose_name='邮编')),
                ('phone', models.CharField(max_length=16, verbose_name='邮编')),
                ('fix', models.CharField(max_length=16, verbose_name='邮编')),
                ('Email', models.EmailField(max_length=254, verbose_name='邮编')),
            ],
        ),
    ]
