# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='咨询人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('project', models.CharField(max_length=128, verbose_name='项目名称')),
                ('msg', models.TextField(verbose_name='咨询内容')),
                ('status', models.BooleanField(default=0, verbose_name='审核状态')),
            ],
            options={
                'verbose_name_plural': '咨询状态',
            },
        ),
        migrations.AlterModelOptions(
            name='filiale',
            options={'verbose_name_plural': '分支机构'},
        ),
        migrations.AddField(
            model_name='filiale',
            name='img',
            field=models.ImageField(default='0', upload_to='upimg', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiale',
            name='status',
            field=models.BooleanField(default='1', verbose_name='显示/关闭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiale',
            name='weight',
            field=models.SmallIntegerField(default='1', verbose_name='权重'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filiale',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='filiale',
            name='fix',
            field=models.CharField(max_length=16, verbose_name='传真'),
        ),
        migrations.AlterField(
            model_name='filiale',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='filiale',
            name='zipcode',
            field=models.IntegerField(default=0, null=True, verbose_name='邮编'),
        ),
    ]
