# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0002_auto_20170606_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('introduce', models.CharField(max_length=10, verbose_name='业务介绍')),
                ('img', models.ImageField(upload_to='business', verbose_name='图片')),
                ('weight', models.SmallIntegerField(verbose_name='权重')),
                ('status', models.BooleanField(verbose_name='显示/关闭')),
            ],
            options={
                'verbose_name_plural': '业务介绍',
            },
        ),
    ]
