# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0003_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='introduce',
            field=models.CharField(max_length=360, verbose_name='业务介绍'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.BooleanField(default=0, verbose_name='显示/关闭'),
        ),
        migrations.AlterField(
            model_name='business',
            name='weight',
            field=models.SmallIntegerField(default=1, verbose_name='权重'),
        ),
    ]
