# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0004_auto_20170606_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='关于我们')),
            ],
        ),
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('img', models.ImageField(upload_to='case', verbose_name='图片')),
                ('content', models.TextField(verbose_name='内容')),
                ('weight', models.SmallIntegerField(default=1, verbose_name='权重')),
                ('status', models.BooleanField(default=0, verbose_name='显示/关闭')),
                ('ctime', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '客户案例',
            },
        ),
    ]
