# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0006_auto_20170606_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zhaopinmodel',
            options={'verbose_name_plural': '招聘信息'},
        ),
        migrations.AddField(
            model_name='zhaopinmodel',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zbxc.Filiale', verbose_name='招聘公司'),
            preserve_default=False,
        ),
    ]
