# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0007_auto_20170606_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhaopinmodel',
            name='nature',
            field=models.SmallIntegerField(choices=[(1, '全职'), (2, '兼职'), (3, '其他')], default=1, verbose_name='工作性质'),
        ),
        migrations.AddField(
            model_name='zhaopinmodel',
            name='nub',
            field=models.SmallIntegerField(default=1, verbose_name='招聘人数'),
        ),
    ]
