# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxc', '0009_auto_20170817_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='img',
            field=models.CharField(max_length=255, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='img',
            field=models.CharField(max_length=255, verbose_name='图片'),
        ),
    ]
